### ISSUE TITLE
Composer install not working

### ISSUE THREAD

**Issue by HashandSalt** [bvdputte/kirby-fingerprint#1]
You need to release and tag 👍

**Comment by bvdputte** [comment]
Can you help me out a bit how I do this? I'm not an experienced composer user 😅

Is this why I need packagist?

**Comment by HashandSalt** [comment]
Sure.... it confused me too. Yes, you need a packagist account first. Then tag a commit with a semver number like v1.0.1, push it, then in Github create release using that version number. Then go back to packagist and submit the url to the repo. It will pick up the version tag of the release. It does it this way so it knows the difference between stable releases and dev releases.

**Comment by HashandSalt** [comment]
Then going forward you just tag new version numbers, and make a release from it in Github - packagist will pick it up automatically.

**Comment by bvdputte** [comment]
Thanks! I added it: https://packagist.org/packages/bvdputte/kirby-fingerprint

Could you test if it works now?

**Comment by HashandSalt** [comment]
Sure.. just tried it and its all good now 👍

**Comment by bvdputte** [comment]
Thx for your help, James 🙌
