### ISSUE TITLE
composer version not updated: parameter option not working

### ISSUE THREAD

**Issue by scsskid** [bvdputte/kirby-fingerprint#11]
Thanks for the plugin!

Using 2.1 the parameter option is not working (its using hashes), default hash name works, I need also this to work with laravel valet (you mentioned in readme)

But I guess I'm disabling the plugin for local development

**EDIT:**

I peeked into the code, I guess you didnt update the composer version
The Code from Github works

**Comment by iskrisis** [comment]
Confirmed. Its just matter of making github release and composer will work.
You can require it like this
`"bvdputte/kirby-fingerprint": "dev-master"` in meantime but it might be a bit dangerous if master keeps updating and something there breaks.

**Comment by bvdputte** [comment]
Sorry. Fixed this!

https://github.com/bvdputte/kirby-fingerprint/releases/tag/v2.2
