### ISSUE TITLE
Undefined variable $filename

### ISSUE THREAD

**Issue by bezin** [bvdputte/kirby-fingerprint#12]
Hello there,

while I skimmed through your code my IDE showed me an undefined variable error in `Fingerprint::Hash`: https://github.com/bvdputte/kirby-fingerprint/blob/master/src/Fingerprint.php#L35

Best
Benedict

**Comment by bvdputte** [comment]
Hi Benedict,

What exactly is undefined please?
In case there's something fishy to `$path` or it's `pathinfo`, you shouldn't get to this line?

**Comment by bezin** [comment]
Hi Bart, 

I am sorry, the link pointed to the wrong line. It is now fixed. In line 35 you return `$filename` which was never defined.

**Comment by bvdputte** [comment]
You're right. Seems to be leftover code that didn't do anything.

I've removed it. Thx 👍
