### ISSUE TITLE
add version field to composer.json 

### ISSUE THREAD

**Issue by jonaskuske** [bvdputte/kirby-fingerprint#13]
Kirby 3.8 uses the `"version"` field in `composer.json` to check whether installed plugins are up-to-date, so it would be great if `kirby-fingerprint` could increment it alongside the git tags.

https://getkirby.com/releases/3.8/migration-plugins#add-compatibility-with-the-update-check

**Comment by bvdputte** [comment]
Sorry, I'm not the best composer user...

Should be fixed in 2.2.5

**Comment by jonaskuske** [comment]
That was fast! Thanks! 😊
