### ISSUE TITLE
@auto rule causes empty <link> or <script>

### ISSUE THREAD

**Issue by bezin** [bvdputte/kirby-fingerprint#6]
Hi, as I mentioned in the PR, the way it works now adds an empty <link> or <script> when using @auto and you don't have a template specific asset. The only way to circumvent this as long as the kirby issue is not resolved, is to use custom helper functions instead of the kirby core functions. 

Cheerio

**Comment by bvdputte** [comment]
This should be [fixed in 3.1.2](https://github.com/getkirby/kirby/issues/1608#issuecomment-477226580).

Probably not what you want to hear, but maybe _we just live with it for a little bit longer_, as the core team intends to release patch releases at a frequent interval? 😅

**Comment by bezin** [comment]
Fine with me 👍
